apiVersion: v1
kind: ConfigMap
metadata:
  name: life-assistant-config
data:
  app-version: dev
  nacos-server-addr: nacos:8848
  nacos-config-server-addr: nacos:8848
  nacos-config-group: DEFAULT_GROUP
  nacos-config-namespace: ""
  nacos-config-refresh-enabled: "true"
  user-datasource-url: jdbc:mysql://mysql:3306/user_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&allowPublicKeyRetrieval=true
  merchant-datasource-url: jdbc:mysql://mysql:3306/merchant_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  order-datasource-url: jdbc:mysql://mysql:3306/order_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  settlement-datasource-url: jdbc:mysql://mysql:3306/settlement_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  fulfillment-datasource-url: jdbc:mysql://mysql:3306/fulfillment_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&allowPublicKeyRetrieval=true
  engagement-datasource-url: jdbc:mysql://mysql:3306/engagement_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&allowPublicKeyRetrieval=true
  spring-sql-init-mode: "never"
  redis-host: redis
  redis-port: "6379"
  redis-database: "0"
  app-upload-root-dir: /app/uploads
  app-upload-review-dir: /app/uploads/reviews
  app-upload-max-image-size-bytes: "20971520"
  oss-enabled: "true"
#  oss-endpoint: oss-cn-heyuan.aliyuncs.com
  oss-endpoint: oss-cn-heyuan-internal.aliyuncs.com
  oss-bucket: buaa-summer-life-assistant
  oss-public-base-url: /oss
  oss-upload-prefix: life-assistant
  oss-cname-enabled: "false"
  spring-servlet-multipart-max-file-size: 20MB
  spring-servlet-multipart-max-request-size: 120MB
  app-auth-captcha-enabled: "true"
