apiVersion: v1
kind: Secret
metadata:
  name: life-assistant-secret
type: Opaque
stringData:
  mysql-root-password: "123456"
  jwt-secret: "LifeAssistant2025SecretKeyForJWTTokenGenerationMustBe256BitsLong"
