plugins {
    id 'java-library'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.1.0-SNAPSHOT'
description = 'microservice-common'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    maven { url = uri('https://maven.aliyun.com/repository/public') }
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom 'org.springframework.boot:spring-boot-dependencies:3.4.4'
        mavenBom 'org.springframework.cloud:spring-cloud-dependencies:2024.0.1'
        mavenBom 'com.alibaba.cloud:spring-cloud-alibaba-dependencies:2023.0.3.3'
    }
}

dependencies {
    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.boot:spring-boot-starter-aop'
    api 'org.springframework.boot:spring-boot-starter-data-redis'
    api 'org.springframework.boot:spring-boot-starter-validation'
    api 'org.springframework.cloud:spring-cloud-openfeign-core'
    api 'com.alibaba.csp:sentinel-core:1.8.8'
    api 'com.alibaba.csp:sentinel-spring-webmvc-v6x-adapter:1.8.8'
    api 'com.baomidou:mybatis-plus-spring-boot3-starter:3.5.7'
    api 'io.jsonwebtoken:jjwt-api:0.12.5'
    api 'cn.hutool:hutool-all:5.8.28'
    api 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0'

    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.5'

    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
